stages:
  - deploy
  - run

image: maven:3.8.6-openjdk-11

variables:
  MVN_HOME: "/usr/local/apache-maven-3.8.6/bin"

deploy:
  stage: deploy
  script:
    - ${MVN_HOME}/mvn package

run:
  stage: run
  script:
    - sudo nohup java -jar target/demo-1.0.0-DEPLOY.jar &