stages:
  - deploy
  - run

# cache:
#   key: target_folder
#   paths:
#     - ./target

deploy:
  tags:
    - main
  only:
    - main
  stage: deploy
  script:
    - sh ./shellscripts/deploy.sh

run:
  tags:
    - main
  only:
    - main
  stage: run
  script:
    - sh ./shellscripts/run.sh
